Search : Search.o Sequential-Search.o Binary-Search.o
	g++ -o Search Search.o Sequential-Search.o Binary-Search.o

Search.o : Search.cpp
	g++ -c -o Search.o Search.cpp

Sequential-Search.o : Sequential-Search.cpp
	g++ -c -o Sequential-Search.o Sequential-Search.cpp

Binary-Search.o : Binary-Search.cpp
	g++ -c -o Binary-Search.o Binary-Search.cpp

clear :
	rm *.o Search