smatching : smatching.o main.o
	g++ -o smatching smatching.o main.o

smatching.o : smatching.cpp
	g++ -c -o smatching.o smatching.cpp

main.o : main.cpp
	g++ -c -o main.o main.cpp

clear :
	rm *.o smatching